[package]
name = "wkb-raster"
version = "0.1.0"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
